### ISSUE TITLE
Open API generation issue - tags not honoring slashes

### ISSUE THREAD

**Issue by RaviVaranasi** [cesarParra/apexdocs#103]
When generating an open-API specification with a URL with `v1/items`, the generated tag does not include slashes. It generates `v1items`. Below is a snippet of the open-API specification file

```
   "v1/items/": {
      "get": {
        "tags": ["Vitems"],
....
```

**Comment by cesarParra** [comment]
I'm taking a look at this

**Comment by cesarParra** [comment]
Should hopefully be all good in v2.20.0. Please let me know if you run into any issues.
