### ISSUE TITLE
Sort Class methods alphabetically

### ISSUE THREAD

**Issue by ReiSuzuki** [cesarParra/apexdocs#109]
Is there a way to sort all the methods in an apex class alphabetically? This would be useful in some of the classes that have methods that are not alphabetical in the code itself.

**Comment by cesarParra** [comment]
I've released a prototype of this in beta [2.23.0](https://www.npmjs.com/package/@cparra/apexdocs/v/2.23.0-beta.0).

A new argument flag can be provided (either when running the tool through the CLI or through a config file) called `sortMembersAlphabetically` to achieve the desired outcome.

I'll be releasing to GA by end of week if it looks good or if there's no feedback.

**Comment by ReiSuzuki** [comment]
Excellent, will give this a try. Thanks!

**Comment by cesarParra** [comment]
Added in https://github.com/cesarParra/apexdocs/releases/tag/v2.23.0
