### ISSUE TITLE
zsh: command not found: apexdocs-generate

### ISSUE THREAD

**Issue by ofarras** [cesarParra/apexdocs#11]
Hi,

after install using instructions I can't launch apexdocs-generate and show this error:
zsh: command not found: apexdocs-generate

Thanks in advance

Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (1 day ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by lucam75** [comment]
Hi, in your package.json, inside the"scripts", add the specified command with an alias. Something like `"createdocumentation" : "apexdocs-generate -s ./force-app/main/default -t ./classes-documentation -r"`

Now, in your terminal execute `npm run createdocumentation`

It works for me.

**Comment by mani2246** [comment]
i had the same issue even after adding the run script to package,json file. For now i run it using the binary file like this.
`./node_modules/.bin/apexdocs-generate -s force-app/main/default/classes -t docs -g jekyll -c docs/apexdocs-config.json -p global private public`

**Comment by jclark-dot-org** [comment]
You can run it with `npm-exec`:

```
npm exec -- apexdocs-generate <params>
```

Note the double dash required after `npm exec`.
