### ISSUE TITLE
Remove Group name from markdown

### ISSUE THREAD

**Issue by ReiSuzuki** [cesarParra/apexdocs#110]
When generating docs with a group, apexdocs automatically adds the Markdown **Group** <Group Name> to all the files. Is there a way to turn this off?

**Comment by cesarParra** [comment]
There's no way to turn this off currently, but let me look into better ways to configure which attributes get displayed or not

**Comment by cesarParra** [comment]
I'm still planning on taking a look at this, but it might take a while since I don't want to just a flags to turn certain things on/off ad-hoc. Instead I need to come up with a way for the final layout/output to be configured in a more generic way.

**Comment by ReiSuzuki** [comment]
Excellent, thanks @cesarParra.

**Comment by cesarParra** [comment]
The latest version of the tool (3.0.0) improves upon this by allowing for a config property ("excludeTags") to be provided that will filter out any documentation tag that should not be added to the final documentation output.
