### ISSUE TITLE
Method Return Types not documented correctly

### ISSUE THREAD

**Issue by mani2246** [cesarParra/apexdocs#12]
If we add a space in the method return type (space between `,` and `Object` here). The space breaks the documentation. the return type in the Markdown file only contains `Object>`

`public static` **Map<String, Object>** `getActiveSurveySettings(String surveyType){ ... }`
![image](https://user-images.githubusercontent.com/13785524/116221413-def74700-a74d-11eb-8e77-34c3f1b660f1.png)

If we remove the space it works as expected.

`public static` **Map<String,Object>** `getActiveSurveySettings(String surveyType){ ... }`
![image](https://user-images.githubusercontent.com/13785524/116220767-43fe6d00-a74d-11eb-973f-7ebedcc4cd97.png)

**Comment by cesarParra** [comment]
Thanks!

Issue should not be resolved in the latest version (1.12.0)
