### ISSUE TITLE
Document class without a class modifier

### ISSUE THREAD

**Issue by mani2246** [cesarParra/apexdocs#15]
Thanks for fixing the other issues like a super human 💯 
I noticed that the tool does not create Markdown files for classes without access modifier.
Example:

@isTest
class TestObjectFactory { ... }

**Comment by cesarParra** [comment]
No problem! 

I've been looking into this one but it has proved to be a quite a bit more tricky than the last one 😅

**Comment by cesarParra** [comment]
Sorry it took this long for me to get back to this. The tool as it was written was pretty inflexible when making changes to the way the parser worked, so I couldn't do much on that state. I've released v2 of the tool where I've rewritten the parsing logic and this is now supported on that version.

If you decide to upgrade let me know if you run into any issues or missing features.
