### ISSUE TITLE
Open API Feature removes leading slashes from paths entries

### ISSUE THREAD

**Issue by scottpopplewell** [cesarParra/apexdocs#194]
# Summary
Open API files typically have leading `/`s for paths keys. Do you have any more context on [this commit](https://github.com/cesarParra/apexdocs/commit/b26e786b629f0da5b23438bed397e2de0573b638) which intentionally removes leading slashes from paths entries?

## Current Behavior

Apexdocs removes the leading `/` from any path defined in `@RestResource(urlMapping=...`. Typically `paths` entries have a leading slash so that when appending with a `servers` entry, the resulting URL is a valid URL.

## Expected Behavior

Apexdocs leaves the leading `/`.

## Further Reading

Checkout [this base Spectral rule](https://support.stoplight.io/s/article/Error-paths-property-must-not-have-unevaluated-properties) which validates that paths have a leading `/` and [documentation from SmartBear aka Swagger ](https://swagger.io/docs/specification/v3_0/paths-and-operations/) which describes creating paths with leading slashes.

**Comment by cesarParra** [comment]
Good call @scottpopplewell . When this was developed it was done targeting an internal tool which from what I recall was having issues with the leading slash. But this should definitely respect the specification. I'll look into this

**Comment by cesarParra** [comment]
The latest version (3.3.2) contains the changes.
