### ISSUE TITLE
Add support to show pick list values in Custom Object

### ISSUE THREAD

**Issue by RaviVaranasi** [cesarParra/apexdocs#205]
The goal is to render the picklist values in a custom object documentation generator.

I have started with the changes locally. Should I issue a PR from a branch or create a fork and issue a PR?

Let me know and thanks for well factored code and tests 🥇

**Comment by cesarParra** [comment]
That's awesome @RaviVaranasi .

For the PR you will probably need to fork and issue a PR, since to create a branch PR write access is needed

**Comment by cesarParra** [comment]
Now available in version 3.5+.

Thanks @RaviVaranasi  for the contribution!
