### ISSUE TITLE
v3 breaking change: recursive file/folder traversal

### ISSUE THREAD

**Issue by pozil** [cesarParra/apexdocs#216]
Hi @cesarParra it's been some time since I haven't revisited your work so congrats for the v3 releases.

I'm trying to upgrade [Apex Recipes](https://github.com/trailheadapps/apex-recipes) to the latest version of apexdocs and I realize that there's an undocumented change of behavior likely introduced in v3.

In v2, I would run:
```sh
apexdocs-generate -p global public private protected namespaceaccessible -s force-app/main/default/classes
```

Based on the v3 docs, I assume that I now need to run this command for the same results (new bin file name, `markdown` param, required quotes for scopes):
```sh
apexdocs markdown -p "global public private protected namespaceaccessible" -s force-app/main/default/classes
```

This command executes without error but it doesn't cover any apex files (I only get an empty `index.md`). I assume that it has to do with the recursive behavior change introduced in v3 and the specific structure of Apex Recipes with some intermediate "recipe group" folders likes this:
```
force-app/main/default/classes/
  Async Apex Recipes/
    file1.cls
    file2.cls
    ...
  Collection Recipes/
    file1.cls
    file2.cls
    ...
  ...
```

Does this qualify as a bug or is it the new expected behavior?

**Comment by pozil** [comment]
Additional investigations:
- running the above v3 command takes some time so I think that the tool is indeed parsing the Apex files but it doesn't output anything
- if I change the above command to point to a specific folder that contains Apex files directly such as `force-app/main/default/classes/Async Apex Recipes` it doesn't output anything as well.

**Comment by cesarParra** [comment]
Thanks @pozil 

Yeah, I would say that is a bug. Ideally all .cls files are found no matter where they are. The only "breaking" change expected is that now the accompanying `meta.xml` file should be present, whereas that wasn't a requirement before

**Comment by cesarParra** [comment]
Actually, the issue seems to be because of the quotes `"` in the scopes (`-p`) argument. Without those you should get the desired output:

`apexdocs markdown -p global public private protected namespaceaccessible -s force-app/main/default/classes`

**Comment by pozil** [comment]
Damn, sorry, and thanks for the quick reply.

I added the quotes because the command was complaining about the "public" value. I initially thought that it was because of the missing quotes but in fact, it was because I hadn't added the `markdown` parameter in my first attempt.
