### ISSUE TITLE
Return types using angle bracket notation - List<String>, Map<String, String>, etc

### ISSUE THREAD

**Issue by mattisdada** [cesarParra/apexdocs#22]
Any return type, parameter type, etc, that uses angle bracket notations causes issues with the output, especially when the output is not in a code block as this will get picked up by most Markdown parsers as HTML instead and effectively render nothing. 

It also causes issues if plugging this into other rendering systems that accept MDX.

If not within a code block, `&gt;` and `&lt;` can be used as an escape

**Comment by cesarParra** [comment]
Thanks for raising this up and the suggestion @mattisdada !

The tool now encodes any HTML character outside of the examples block with the v1.13.4 release, which should fix the issue.

**Comment by mattisdada** [comment]
Perfect, thanks a bunch @cesarParra <3
