### ISSUE TITLE
Feature request: accept single source file as CLI input

### ISSUE THREAD

**Issue by pozil** [cesarParra/apexdocs#32]
First of all, thanks for this great tool. We're using it several project including the [Apex Recipes](https://github.com/trailheadapps/apex-recipes) sample app.

As part of our dev workflows we use [lint-staged](https://github.com/okonet/lint-staged) to automatically run [some pre-commit scripts](https://github.com/trailheadapps/apex-recipes/blob/main/package.json#L22) on files that are staged (not the entire repo):
- formatting with Prettier
- linting with ESLint
- LWC tests with Jest.

It would be great if we could add apexdocs to this workflow. However, in order to achieve this and make apexdocs work with lint-staged, we need the apexdocs CLI to accept an individual source file instead of an entire source directory.
Is this a feature that you would consider?

**Comment by cesarParra** [comment]
Thanks @pozil !

I really like the suggestion, I can make that happen

**Comment by pozil** [comment]
Wonderfull, thanks for the quick reply. We're happy to help you test if you'd like.
FYI @codefriar.

**Comment by cesarParra** [comment]
@pozil I have a few questions to see how to best tackle this:
* I'm assuming that you'd want the generation of the home file to be skipped when generating one-off, right?
* What about linking in between files (using the `@see` annotation and inline `{@link FileName}` link)? Are you relying on that today.
** This one is more of an issue when combined with the use of `@group` as groups of classes are put in different directories so I need to know of to be able to generate the hyperlink.

Both of those operations rely on having a reference to all files for which the docs are being generated to create references and hyperlinks to all other files, so when generating files one by one they'd be missing that information. Those operations could be skipped but making sure that'd be ok.

**Comment by pozil** [comment]
These are great questions and must admit that I hadn't thought about this before. The dependencies between files really makes this feature more tricky to implement.
We don't use the home file in our project but we heavily rely on `@see` and `@group` so I can imagine how this would cause problems.
As you pointed out, skipping the link operations might break docs so I don't think that it's a viable option. It could very well happen that this feature can't be implemented at a reasonable cost.

**Comment by codefriar** [comment]
While I sympathize with @pozil's request, I have to agree that this isn't feasible, at least without a major refactor.

**Comment by pozil** [comment]
Closing this since I don't think that my request is realistic given the file dependency constraints. Thanks for considering it.
