### ISSUE TITLE
Param parsing on multiple lines

### ISSUE THREAD

**Issue by codefriar** [cesarParra/apexdocs#4]
First,

Let me say GREAT work. I love this.

I've discovered an issue where it's unable to properly determine parameters when they are on multiple lines. This causes issues with the default prettier config that forces param lists to wrap to one-per-line if the overall line exceeds 80 characters.

Example code to reproduce:

```apex
    /**
     * @description - This method is where the actual work occurs. It's run once per batch.
     * @param context - dependency injected by the system
     * @param scope - a list of up to 200 SObject records to be processed
     *   in this batch. It's this mechanism of breaking a large number of records
     *   into smaller batches called scope (in this example) that make this easier
     **/
    public void execute(
        Database.BatchableContext context,
        List<Account> scope
    ) { }
```

This generates the following markdown:

```markdown
---
## Methods
### `)` → ``

- This method is where the actual work occurs. It's run once per batch.
#### Parameters
|Param|Description|
|-----|-----------|
|`context` |  - dependency injected by the system |
|`scope` |  - a list of up to 200 SObject records to be processed |
```

Specifically, the issue is here:

```markdown
### `)` → ``
```

**Comment by cesarParra** [comment]
Thanks @codefriar ! I'm looking into it.

**Comment by codefriar** [comment]
Thanks!

**Comment by cesarParra** [comment]
New version (1.10.1) has been released with the fix. Thanks for bringing up the issue!

**Comment by codefriar** [comment]
Amazing!

Have you given any thought to putting this in a sfdx plugin?

**Comment by cesarParra** [comment]
I had not, but I definitely have to look into that!
