### ISSUE TITLE
No docGenerator function in export

### ISSUE THREAD

**Issue by alpha-bytes** [cesarParra/apexdocs#46]
Good afternoon. Just installed from npm @ `v2.2.2` and tried importing into my nodejs script. The documentation indicates there's a `docGenerator` function that should be part of the export but I wasn't able to find it anywhere: 

> If you are just interested in the documentation parsing capabilities, you can import ApexDocs into your own project.
>
> Use the docGenerator function to create a list of ClassModel that includes all the parsed information from your .cls files [...]

**Comment by cesarParra** [comment]
Ah, that's my bad. That note was for versions 1.X. For versions 2.X on the parsing logic has been moved to its own module: https://www.npmjs.com/package/@cparra/apex-reflection

Hopefully that helps. I will update the docs to clarify

**Comment by cesarParra** [comment]
Closing this for now. Feel free to reopen if you face any other issues.
