### ISSUE TITLE
Bit more multi-line weirdness

### ISSUE THREAD

**Issue by codefriar** [cesarParra/apexdocs#5]
Cesar,

Again, thank you for your work on this and your responsiveness. 

I've hit upon another bit of wonky parsing, and I'm not sure what to make of it. Here's the Apex method causing troubles

```apex
/**
     * @description - Demonstrates how to use the Database.insert() method to persist a net-new
     *  record to the database.
     * @param  name         name Passed through to the account created
     * @param  allOrNothing allOrNothing determines whether or not all accounts to be inserted must insert successfully
     */
    public static void insertAccountsViaDatabaseMethod(
        String name,
        Boolean allOrNothing
    ) {
        Account acct = new Account(name = name);
        Account acct2 = new Account();

        try {
            if (CanTheUser.create(acct)) {
                Database.insert(new List<Account>{ acct, acct2 }, allOrNothing);
            }
        } catch (DMLException DMLe) {
            throw new CustomDMLException('Failed');
        }
    }
```

It's generating this markdown

```markdown
---
## Methods
### `)` → ``

- Demonstrates how to use the Database.insert() method to persist a net-new record to the database.
#### Parameters
|Param|Description|
|-----|-----------|
|`name` |          name Passed through to the account created |
|`allOrNothing` |  allOrNothing determines whether or not all accounts to be inserted must insert successfully |
```

Specifically, it's not properly parsing the method name, and I'm not sure why. 4 methods in this file (I gave one example above) fail to parse, but the other ~5-6 work fine.

**Comment by cesarParra** [comment]
🤔 This one I don't seem to be able to replicate after this morning's update. I've updated the `examples` repo with the code and it's resolving fine there: code https://github.com/cesarParra/apexdocs-docsify-example/blob/master/classes/Test.cls and resulting file - https://cesarparra.github.io/apexdocs-docsify-example/#/Miscellaneous/Test

I wonder if the issue occurs when pairing it with something else in the file, thus it failing for some but not for others.

**Comment by codefriar** [comment]
Well, let me post the full file, and see.

**Comment by codefriar** [comment]
Ok, so egg all over my face. This was a pebkac issue. i'd switched branches and didn't bring my package.json along. Please forgive me.

**Comment by cesarParra** [comment]
Not a problem, glad it's working 😄
