### ISSUE TITLE
Allow for empty @argument, @return, and other tags

### ISSUE THREAD

**Issue by cesarParra** [cesarParra/apexdocs#51]
Currently the parser for docs complains about empty `@argument`, `@return`, and possible other tags where it expects some kind of body. Maybe we can allow for this without the parser complaining and simply not have a description for those that are empty

**Comment by carrera328** [comment]
I'm adding a @return to my comments but not seeing that return being parse. The markdown generates a return block but my text isn't picked when the parsing is done.

**Comment by carrera328** [comment]
# IdeaFeatureFlagSelector

`APIVERSION: 55`

`STATUS: ACTIVE`

"Selector" Class for querying Feature Flag Custom Metadata Records.


**Author** IDEA Development Team


**See** [https://andyinthecloud.com/2013/09/09/apex-enterprise-patterns-selector-layer/](https://andyinthecloud.com/2013/09/09/apex-enterprise-patterns-selector-layer/)

## Fields

### `sObjectFields` → `List<Schema.SObjectField>`


The below list of fields are always returned whenever this class is instantiated

---
## Methods
### `static isValidQuery(String query)`

Static method that checks whether a provided query is a valid query or not

#### Parameters

|Param|Description|
|---|---|
|`query`|Query to validate against|

#### Return

**Type**

Boolean

**Description**

`Boolean if whether or not provided query is valid`

### `getSObjectType()`

Returns the sObject type of this selector

#### Return

**Type**

Schema.SObjectType

**Description**

sObject type

### `getSObjectFieldList()`

Returns the "default" list of fields that this selector class returns

#### Return

**Type**

List&lt;Schema.SObjectField&gt;

**Description**

`List&lt;Schema.SObjectField&gt;`List of `IDEA_Feature_Flag__mdt` fields

### `addSObjectFields(List<Schema.SObjectField> sObjectFields)`

Adds additional sObject fields to query (outside of "default" set)

#### Parameters

|Param|Description|
|---|---|
|`sObjectFields`|List of `IDEA_Feature_Flag__mdt` fields|

### `generateQueryString()`

Generates a query string from the sObject fields contained in this class

#### Return

**Type**

String

**Description**

Base query string

### `setQueryCondition(String queryString, String queryCondition)`

Appends a condition to a query

#### Parameters

|Param|Description|
|---|---|
|`queryString`|Base query string|
|`queryCondition`|Conditional string for a query|

#### Return

**Type**

String

**Description**

Query string with a provided condition

### `selectByComponent(Set<String> componentApiNames)`

Returns a list of Feature Flag records based on API names of LWCs

#### Parameters

|Param|Description|
|---|---|
|`componentApiNames`|Set of API names of LWC components|

#### Return 

**Type**

List&lt;IDEA_Feature_Flag__mdt&gt;

**Description**

List of Feature Flag records

---
## Classes
### IDEAQueryException

---

**Comment by cesarParra** [comment]
Thanks @carrera328

I'll look into this

**Comment by cesarParra** [comment]
@carrera328 From your second comment I see the return information there 

![image](https://user-images.githubusercontent.com/2524257/187884454-03ad58ad-b5b1-43ed-8da6-8c11b34dfcaa.png)

Is the issue that the text doesn't match what you have or that the current format is not clear?

**Comment by carrera328** [comment]
Hey @cesarParra I see now, my mistake I misunderstood the format. Thanks for clearing this up for me.
