### ISSUE TITLE
Nothing being generated

### ISSUE THREAD

**Issue by Kenji776** [cesarParra/apexdocs#53]
It's me again, go figure haha. So since the most recent update I'm not able to get any output. It will iterate through the input files, say it's parsing, then say 0 files parsed. I don't know if its erroring on the files silently or for some reason considering them invalid? Not sure if there is a debug log or verbose mode that isn't documented but I'm not really sure how to debug this. I can send you my files that I'm trying to parse if that helps. It does generate the index.md file but it seems to be corrupt/incomplete. Let me know if there is any other info I can provide to help. Thanks!

![image](https://user-images.githubusercontent.com/2421263/171473056-b5864c95-7dd5-4ebf-b198-c64e96d13354.png)

![image](https://user-images.githubusercontent.com/2421263/171473134-e9c0a6d8-fd0f-4e98-adc8-953d1d8ed08d.png)

**Comment by Kenji776** [comment]
Yes, this seems to be a new issue with 2.3 as far as I know.

**Comment by cesarParra** [comment]
Closing this for now. Please feel free to reopen if there are any other issues.
