### ISSUE TITLE
@start-group doesn't like quotes

### ISSUE THREAD

**Issue by jclark-dot-org** [cesarParra/apexdocs#57]
This works perfectly:

```
public class ApexUtil {

    // @start-group allOrNothing param values DML Operations
    public static final Boolean ALLOW_PARTIAL_SUCCESS = false;
    public static final Boolean ALL_OR_NOTHING = true;
    // @end-group

    // @start-group caseSensitive param values for ApexUtil.getPattern()
...
```

But if I add backticks (or single- or double-quotes) around the first word of the group description, it does not:
```
public class ApexUtil {

    // @start-group 'allOrNothing' param values DML Operations
    public static final Boolean ALLOW_PARTIAL_SUCCESS = false;
    public static final Boolean ALL_OR_NOTHING = true;
    // @end-group

    // @start-group caseSensitive param values for ApexUtil.getPattern()
...
```

Resulting in:
>  7/8/2022, 9:15:47 AM: ApexUtil.cls - Parsing error Exception: Error parsing Apex Body. Line 14:4 - extraneous input '// @end-group' expecting {'abstract', 'after', 'before', 'class', 'enum', 'final', 'get', 'global', 'inherited', 'instanceof', 'interface', 'override', 'private', 'protected', 'public', 'set', 'sharing', 'static', 'switch', 'testmethod', 'transient', 'trigger', 'virtual', 'void', 'webservice', 'when', 'with', 'without', 'list', 'map', 'select', 'count', 'from', 'as', 'using', 'scope', 'where', 'order', 'by', 'limit', 'and', 'or', 'not', 'avg', 'count_distinct', 'min', 'max', 'sum', 'typeof', 'end', 'then', 'like', 'in', 'includes', 'excludes', 'asc', 'desc', 'nulls', 'first', 'last', 'group', 'all', 'rows', 'view', 'having', 'rollup', 'tolabel', 'offset', 'data', 'category', 'at', 'above', 'below', 'above_or_below', 'security_enforced', 'reference', 'cube', 'format', 'tracking', 'viewstat', 'custom', 'standard', 'calendar_month', 'calendar_quarter', 'calendar_year', 'day_in_month', 'day_in_week', 'day_in_year', 'day_only', 'fiscal_month', 'fiscal_quarter', 'fiscal_year', 'hour_in_day', 'week_in_month', 'week_in_year', 'converttimezone', 'yesterday', 'today', 'tomorrow', 'last_week', 'this_week', 'next_week', 'last_month', 'this_month', 'next_month', 'last_90_days', 'next_90_days', 'last_n_days', 'next_n_days', 'next_n_weeks', 'last_n_weeks', 'next_n_months', 'last_n_months', 'this_quarter', 'last_quarted', 'next_quarter', 'next_n_quarters', 'last_n_quarters', 'this_year', 'last_year', 'next_year', 'next_n_years', 'last_n_years', 'this_fiscal_quarter', 'last_fiscal_quarter', 'next_fiscal_quarter', 'next_n_fiscal_quarters', 'last_n_fiscal_quarters', 'this_fiscal_year', 'last_fiscal_year', 'next_fiscal_year', 'next_n_fiscal_years', 'last_n_fiscal_years', 

If I insert any text before the quoted word, it's fine... I can even use backticks to get monospaced text as intended.  It just seems to be the first non-space character after `@start-group` that matters.

**Comment by cesarParra** [comment]
Thanks @jclark-dot-org 

I just released a new version with this fix https://github.com/cesarParra/apexdocs/releases/tag/v2.5.1. Let me know if anything is not working.
