### ISSUE TITLE
Feature Request: private methods should be documented

### ISSUE THREAD

**Issue by codefriar** [cesarParra/apexdocs#6]
I'd love a flag, or an option to have the docs also generate method blocks for private methods.

**Comment by cesarParra** [comment]
Hi @codefriar . This is currently possible by using the `--scope` (p) flag and passing `private` as one of the desired scopes. For example:

`apexdocs-generate -s classes -t docs -p global public namespaceaccessible private`

**Comment by codefriar** [comment]
Oh! Amazing!!!

**Comment by cesarParra** [comment]
I did notice some rendering issues with the markdown when outputting descriptions of void private methods (no `param` or `return` on the apex doc) so I'll be releasing a fix for that.
