### ISSUE TITLE
[webpack-cli] [Error: EINVAL: invalid argument, mkdir

### ISSUE THREAD

**Issue by ZaraBaghdasaryan** [cesarParra/apexdocs#71]
Hi,

Could you please help me to resolve the issue with the EINVAL error? I have tried every solution that I could find but still have not had any luck :( 

Thank you so much for all your help in advance!
![3](https://user-images.githubusercontent.com/74423786/220110730-ff9eafcb-d8e9-4527-8b46-c41b4f68ea4b.PNG)

**Comment by cesarParra** [comment]
Hi @ZaraBaghdasaryan 

Yeah I can try and help! Would you mind sharing the command that you are running and the ApexDocs version you are using?

**Comment by ZaraBaghdasaryan** [comment]
Hi @cesarParra, thank you so much for wanting to help! :) I am essentially locating the project I want to start and running the npm run dev command. I don't think I am using ApexDocs library, here are the packages that I use:

argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asgiref==3.5.2
asn1crypto==1.0.1
astroid==2.4.2
autopep8==1.5.4
azure-common==1.1.23
azure-nspkg==3.0.2
azure-storage-common==2.1.0
backports.zoneinfo==0.2.1
certifi==2019.9.11
cffi==1.15.1
chardet==3.0.4
charset-normalizer==2.1.1
cryptography==38.0.4
Django==3.2
django-countries==7.2.1
djangorestframework==3.14.0
gunicorn==20.1.0
idna==2.8
isort==5.7.0
lazy-object-proxy==1.4.3
mccabe==0.6.1
plotly==5.11.0
psycopg2-binary==2.8.6
pycodestyle==2.6.0
pycparser==2.19
PyJWT==1.7.1
pylint==2.6.0
pyOpenSSL==22.1.0
python-dateutil==2.8.0
python-dotenv==0.15.0
pytz==2019.3
requests==2.28.1
sentry-sdk==1.10.1
six==1.12.0
sqlparse==0.3.0
tenacity==8.1.0
toml==0.10.2
urllib3==1.26.12
wrapt==1.12.1

![Skärmklipp](https://user-images.githubusercontent.com/74423786/220579391-2653aef9-a4b2-433e-bc1d-4a09333dbcd2.PNG)

**Comment by cesarParra** [comment]
@ZaraBaghdasaryan 

From the screenshot it doesn't seem like you are working on a Salesforce project or using the ApexDoc tool? If that's the case I'm unfortunately not going to be of help. I'm not really familiar with the tech stack you are working with

**Comment by ZaraBaghdasaryan** [comment]
No worries, thank you so much for wanting to help!
