### ISSUE TITLE
Option to customize the result README title for non openApi generators

### ISSUE THREAD

**Issue by IlyaMatsuev** [cesarParra/apexdocs#73]
Would it be possible to have an option to customize the current `# Classes` title in the result README.md file?
The use case is that I want to group all of my package classes into: Classes/Interfaces/Enums. But this standard `Classes` title in the beginning doesn't seem to make sense in this case as it's the main header.

Expected result:
```md
# My Custom Title
## Classes

### [Service](/Classes/Service.md)

Some service description

## Interfaces

### [IService](/Interfaces/IService.md)
```

Actual result:
```md
# Classes
## Classes

### [Service](/Classes/Service.md)

Some service description

## Interfaces

### [IService](/Interfaces/IService.md)
```

**Comment by cesarParra** [comment]
Available in 2.14.0 with the addition of the `title` flag: https://www.npmjs.com/package/@cparra/apexdocs/v/2.14.0. Let me know if that covers the desired functionality
