### ISSUE TITLE
Docusaurus support

### ISSUE THREAD

**Issue by sjurgis** [cesarParra/apexdocs#74]
Was wondering what would it take for this to generate Docusaurus site? I love how Docusaurus works, but never understood how to implement myself. 
Fuzzy search looks particularly useful!

Cheers

**Comment by cesarParra** [comment]
I like the idea. I'll need to do some research around it and see what the effort would be.

For the search part I believe they integrate with [Algolia ](https://www.algolia.com), which can also be integrated with other platforms.

**Comment by sjurgis** [comment]
I see, didn't know about Algolia part - always assumed it happens locally.
