### ISSUE TITLE
Access Modifiers is missing in the output

### ISSUE THREAD

**Issue by davidbrowaeys** [cesarParra/apexdocs#81]
I really like a lot this tool. So great what you have been doing.

How do you add the method access modifier (global, private, public) to the md file? Seems to be missing for me in the generated output. 

`apexdocs-generate -s force-app -t docs -r --scope global public  private -g docsify --includeMetadata`

<img width="336" alt="image" src="https://user-images.githubusercontent.com/20630942/231661770-c6d4a527-8504-4243-909b-43508e417352.png">

**Comment by cesarParra** [comment]
Thanks @davidbrowaeys 

No way right now, but I agree those should be in there. Let me look into that!

**Comment by cesarParra** [comment]
I've newest a new version (https://www.npmjs.com/package/@cparra/apexdocs) which should include the access modifiers as part of the method and field descriptions. Let me know if you run into any issues!

**Comment by davidbrowaeys** [comment]
Wow thank you so much @cesarParra didn't expect the quick so quick.
