### ISSUE TITLE
Don't parse annotations within comments

### ISSUE THREAD

**Issue by pozil** [cesarParra/apexdocs#88]
First of all thanks for the great work that you do around this tool, this is really helpful.

When running apexdocs on the following code, the parser breaks the class description.
```apex
/**
 * @description Demonstrates the @future syntax and usage
 */
public with sharing class AtFutureRecipes {
}
```

This generate the following doc:
```md
---
layout: default
---
# AtFutureRecipes

Demonstrates the


**Future** syntax and usage


```

The problem is due to the fact that it attempts to parse the `@future` annotation within the description.
Could we prevent nested annotations parsing?

**Comment by cesarParra** [comment]
Thank you @pozil !

This might actually be a consequence of a change a made a few releases ago to allow for single line doc comments, e.g.

```
/** @description this is a single line */
public String myField;
```

but it seems like it might be doing that too aggressively. 

Let me see if there's a compromise here

**Comment by cesarParra** [comment]
Will be pretty tough to do this without breaking that other functionality that I mentioned, but one update I prototyped that'd be simple to implement is allowing for annotations wrapped in ` to essentially be escaped and treated as any other string. What do you think about that? So the code you'd have to write to achieve this would now be:

```
/**
 * @description Demonstrates the `@future` syntax and usage
 */
public with sharing class AtFutureRecipes {
}
``` 

One nice side benefit is that it'd give you the markdown code formatting for free

![image](https://github.com/cesarParra/apexdocs/assets/2524257/9b92a11f-1365-4439-bdf6-0801f2c4c46f)

**Comment by cesarParra** [comment]
Excellent. Yeah, that isn't working on the current version so I'll release a new one with the fix.

**Comment by cesarParra** [comment]
New version with the "escape" support: https://www.npmjs.com/package/@cparra/apexdocs/v/2.16.0

**Comment by pozil** [comment]
Thanks so much for the quick turnaround.
