### ISSUE TITLE
Missing @return parsing ?

### ISSUE THREAD

**Issue by NicolasGach** [cesarParra/apexdocs#9]
Hello Cesar,
First of all thanks for sharing this plugin, what a very useful work ! I've stumbled upon what I believe to be an issue with the parsing of @return statements in the javadoc like structure. Here's the simple dummy class I wrote, and below the generate markdown. No configuration file is used. Happy to help solve this if you'd like, although I'm not sure where to start in the implementation you propose.
````
public class dummyTest {
    /**
     * @description Some description for the class.
     * @param myParam Some input parameter
     * @return a return value
     */
    public String dummyMethod(Integer myParam) {
        return '';
    }
}
````
And the generated markdown : 
<pre>
---
layout: default
---
# dummyTest class
---
### `dummyMethod(Integer myParam)` → `String`

Some description for the class.

#### Parameters
|Param|Description|
|-----|-----------|
|`myParam` |  Some input parameter |

---
</pre>

Thanks again for your work, I can definitely see this plugin gaining a lot of traction and interest seeing the void around proper Javadoc like support for Apex !

**Comment by cesarParra** [comment]
Thanks @NicolasGach . This is definitely a gap. I've merged your PR and will be releasing a new version soon. Thanks a lot!

**Comment by cesarParra** [comment]
v1.11.0 has been released with the fix.
