### ISSUE TITLE
Specify full list/set/map type in method return type

### ISSUE THREAD

**Issue by pozil** [cesarParra/apexdocs#94]
I saw that the latest version of apexdocs adds return types to method signatures and it would be nice if the lists/sets/maps were "fully" typed.

![Screenshot 2023-10-04 at 16 58 40](https://github.com/cesarParra/apexdocs/assets/5071767/3287993e-af62-4d0a-95e7-ab24046faf3c)

For example, the return type in this specific example should be `List<Account>` instead of just `List`.

**Comment by codefriar** [comment]
@pozil - check out the --sanitizeHtml option.

**Comment by pozil** [comment]
Thanks @codefriar but I don't think that this the issue. This line is automatically generated from the method signature.
The return type was not specified in the previous apexdocs version, it's a new feature from v2.17.0.

**Comment by cesarParra** [comment]
Yeah, that's definitely a gap with generic types. Let me look into it.

**Comment by cesarParra** [comment]
Addressed in v2.17.1 https://www.npmjs.com/package/@cparra/apexdocs/v/2.17.1

**Comment by pozil** [comment]
Wow, thanks again for the ultra fast fix :)
