### ISSUE TITLE
Apply code formatting to output parameter type documentation

### ISSUE THREAD

**Issue by pozil** [cesarParra/apexdocs#96]
When generating documentation for our code it would be nice to apply code formatting to the output type of a method:
<img width="829" alt="Screenshot 2023-10-06 at 15 32 27" src="https://github.com/cesarParra/apexdocs/assets/5071767/96fa6c72-ccf6-494c-b9b5-092ed42ec807">

PS: ignore the description part that starts with the code formatted `String`. I'll need to fix my description.

I really appreciate all of your hard work and mention that there's no need to rush a fix for this and to release a version immediately, this can definitely wait.

**Comment by cesarParra** [comment]
Thanks @pozil! This makes sense.

Don't worry about me rushing 😅 , it's all good. I like to keep a bit of time open throughout my week for these kind of things and they have been quick fixes so far

**Comment by pozil** [comment]
Thanks once more!
